name: Setup gradle
description: "Set up your GitHub Actions workflow with a specific version of gradle"
runs:
  using: "composite"
  steps:
    - name: Setup gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: wrapper
        build-scan-publish: true
        build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
        build-scan-terms-of-use-agree: "yes"
